name: Generate Invader

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate contribution invader
        uses: VARDHAMANPATEL23/git-invader@main
        with:
          github_user_name: fawacreates
          outputs: |
            dist/github-contribution-grid-invader.svg

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
